import type { ToolMetadata } from '../types/pdf';

/**
 * Single source of truth for tool catalog metadata (title, description,
 * icon, color, category). Both the catalog grid (App.tsx) and each tool's
 * own view import from here instead of each keeping a separate copy.
 */
export const TOOLS: ToolMetadata[] = [
  {
    id: 'merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one document in your exact preferred sequence.',
    icon: 'Combine',
    color: '#DC2626',
    category: 'organize',
    badge: 'Popular',
    acceptedFiles: 'multiple',
  },
  {
    id: 'split',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    icon: 'Scissors',
    color: '#EA580C',
    category: 'organize',
    acceptedFiles: 'single',
  },
  {
    id: 'organize',
    title: 'Organize PDF',
    description: 'Sort pages of your PDF files however you like. Delete, duplicate, or reorder pages.',
    icon: 'LayoutGrid',
    color: '#7C3AED',
    category: 'organize',
    acceptedFiles: 'single',
  },
  {
    id: 'rotate',
    title: 'Rotate PDF',
    description: 'Rotate your PDF pages however you need. Rotate specific pages or documents at once.',
    icon: 'RotateCw',
    color: '#0891B2',
    category: 'organize',
    acceptedFiles: 'single',
  },
  {
    id: 'crop',
    title: 'Crop PDF',
    description: 'Trim page margins on every side, applied to selected pages or the whole document.',
    icon: 'Crop',
    color: '#DB2777',
    category: 'organize',
    acceptedFiles: 'single',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality directly in your browser.',
    icon: 'Minimize2',
    color: '#10B981',
    category: 'optimize',
    badge: 'Zero Upload',
    acceptedFiles: 'single',
  },
  {
    id: 'watermark',
    title: 'Watermark',
    description: 'Stamp text or an image onto every page — logo overlays, drafts, and confidentiality marks.',
    icon: 'Stamp',
    color: '#EAB308',
    category: 'edit',
    acceptedFiles: 'single',
  },
  {
    id: 'pageNumbers',
    title: 'Page Numbers',
    description: 'Add page numbers with custom position, format, and starting page.',
    icon: 'Hash',
    color: '#C026D3',
    category: 'edit',
    acceptedFiles: 'single',
  },
  {
    id: 'protect',
    title: 'Protect PDF',
    description: 'Encrypt your PDF with AES-256 and a password to prevent unauthorized viewing.',
    icon: 'Lock',
    color: '#334155',
    category: 'security',
    acceptedFiles: 'single',
  },
  {
    id: 'unlock',
    title: 'Unlock PDF',
    description: 'Remove password security from PDFs, making them freely readable and printable.',
    icon: 'Unlock',
    color: '#64748B',
    category: 'security',
    acceptedFiles: 'single',
  },
  {
    id: 'pdfToWord',
    title: 'PDF to Word',
    description: 'Extract text from a PDF into an editable .docx document.',
    icon: 'FileText',
    color: '#2563EB',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'wordToPdf',
    title: 'Word to PDF',
    description: 'Convert a .docx document into a PDF.',
    icon: 'FileType',
    color: '#1E40AF',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'pdfToPpt',
    title: 'PDF to PowerPoint',
    description: 'Turn every PDF page into a slide in a new .pptx presentation.',
    icon: 'Presentation',
    color: '#F59E0B',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'pptToPdf',
    title: 'PowerPoint to PDF',
    description: 'Convert a .pptx presentation into a PDF.',
    icon: 'MonitorPlay',
    color: '#B45309',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'pdfToJpg',
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG image.',
    icon: 'ImageIcon',
    color: '#0EA5E9',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'imageToPdf',
    title: 'JPG to PDF',
    description: 'Convert JPG/PNG images to PDF, one page per image.',
    icon: 'ImagePlus',
    color: '#0369A1',
    category: 'convert',
    acceptedFiles: 'multiple',
  },
  {
    id: 'pdfToMarkdown',
    title: 'PDF to Markdown',
    description: 'Turn a PDF into a Markdown file — perfect for notes and LLMs.',
    icon: 'FileCode',
    color: '#0D9488',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'repair',
    title: 'Repair PDF',
    description: 'Repair a damaged PDF and recover what can be read from it.',
    icon: 'Wrench',
    color: '#65A30D',
    category: 'optimize',
    acceptedFiles: 'single',
  },
  {
    id: 'pdfToExcel',
    title: 'PDF to Excel',
    description: 'Pull tabular data from a PDF into an Excel spreadsheet.',
    icon: 'Table',
    color: '#16A34A',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'excelToPdf',
    title: 'Excel to PDF',
    description: 'Convert an Excel spreadsheet into a PDF.',
    icon: 'FileSpreadsheet',
    color: '#166534',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'pdfToPdfa',
    title: 'PDF to PDF/A',
    description: 'Add archival metadata for long-term PDF/A storage compliance.',
    icon: 'Archive',
    color: '#57534E',
    category: 'security',
    acceptedFiles: 'single',
  },
  {
    id: 'forms',
    title: 'PDF Forms',
    description: 'Fill in a PDF form’s fields and export a completed copy.',
    icon: 'ListChecks',
    color: '#4F46E5',
    category: 'edit',
    acceptedFiles: 'single',
  },
  {
    id: 'sign',
    title: 'Sign PDF',
    description: 'Draw, type, or upload a signature and place it on a page.',
    icon: 'PenLine',
    color: '#9333EA',
    category: 'security',
    acceptedFiles: 'single',
  },
  {
    id: 'htmlToPdf',
    title: 'HTML to PDF',
    description: 'Convert HTML content into a formatted PDF document.',
    icon: 'Code2',
    color: '#F43F5E',
    category: 'convert',
    acceptedFiles: 'single',
  },
  {
    id: 'redact',
    title: 'Redact PDF',
    description: 'Permanently black out sensitive text or images — irrecoverably.',
    icon: 'EyeOff',
    color: '#27272A',
    category: 'edit',
    acceptedFiles: 'single',
  },
  {
    id: 'compare',
    title: 'Compare PDF',
    description: 'Spot visual differences between two versions of a document.',
    icon: 'GitCompare',
    color: '#155E75',
    category: 'organize',
    acceptedFiles: 'multiple',
  },
  {
    id: 'scanToPdf',
    title: 'Scan to PDF',
    description: 'Capture pages with your camera and assemble them into a PDF.',
    icon: 'Camera',
    color: '#EF4444',
    category: 'convert',
    acceptedFiles: 'multiple',
  },
  {
    id: 'editPdf',
    title: 'Edit PDF',
    description: 'Add text and images anywhere on the page, then save the result.',
    icon: 'PenSquare',
    color: '#FB923C',
    category: 'edit',
    acceptedFiles: 'single',
  },
];
