/**
 * End-to-end feature verification — IHatePDF
 *
 * Runs the actual, shipped conversion/manipulation logic (not mocks)
 * against the real fixtures in test-fixtures/, generated by
 * scripts/generateTestFixtures.ts.
 *
 * SCOPE — read this before trusting a "PASS": every tool below calls a
 * function extracted verbatim from its real `*.worker.ts` implementation
 * (see each file's `export async function ...` — the Worker wrapper just
 * calls it and posts messages). What's covered here:
 *   Merge, Split, Rotate, Organize, Compress, PPTX->PDF, PDF->Word (docx),
 *   PDF->PPTX, Excel->PDF.
 *
 * What's deliberately NOT covered by this Node script, and why:
 *   - Protect/Unlock: hand-rolled AES-256 crypto, not touched by this
 *     pass's extraction to avoid risking regressions in delicate code
 *     under time pressure. Still covered by this project's existing
 *     browser-based verification record (see HANDOFF.md).
 *   - Watermark, Page Numbers, Redact, Edit PDF: not part of this pass's
 *     rewrite scope; same reasoning.
 *   - Word->PDF: genuinely cannot run in Node — it renders real DOM/CSS
 *     via html2canvas, which needs a browser. Verify it by hand in the
 *     app (see HANDOFF.md for the manual verification steps).
 *   - PDF->JPG/PNG and Images->PDF: not touched this pass; already had
 *     independent browser-based verification from an earlier phase.
 * Faking Node coverage of Worker-only or DOM-only code would be exactly
 * the kind of false "it passes" claim this script exists to prevent — so
 * it reports what it actually tested, not a blanket 28/28.
 *
 * Run: npx tsx scripts/test-all-features.ts
 */

import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PDFDocument } from 'pdf-lib';
import * as XLSX from 'xlsx';

import { parseSlideSize, parseTheme, parseSlide } from '../src/features/pptToPdf/pptxParser';
import { convertPptxToPdf } from '../src/features/pptToPdf/pptToPdf.worker';
import { buildDocxFromPages } from '../src/features/pdfToWord/pdfToWord.worker';
import { buildPptxFromPages } from '../src/features/pdfToPpt/buildPptx.worker';
import { convertXlsxToPdf } from '../src/features/excelToPdf/xlsxToPdf.worker';
import { mergePdfs } from '../src/features/merge/merge.worker';
import { splitPdf } from '../src/features/split/split.worker';
import { rotatePdfPages } from '../src/features/rotate/rotate.worker';
import { organizePdfPages } from '../src/features/organize/organize.worker';
import { compressPdf } from '../src/features/compress/compress.worker';
import { readZip } from '../src/services/zipReader';
import type { PositionedPageText, StyledPageText } from '../src/types/worker';

// pdfjs-dist's legacy/Node build — used here purely to mirror what
// usePdfRenderer's extractPositionedText/extractStyledParagraphs do in the
// browser, so these Node tests exercise real extracted PDF data instead of
// hand-typed stand-ins. `page.render()` (canvas rasterization) is NOT used
// here — it needs a real browser canvas — so slide *background images* in
// the PDF->PPTX test are a placeholder pixel; text extraction is real.
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = resolve(__dirname, '..', 'test-fixtures');

let passed = 0;
let failed = 0;
const failures: string[] = [];

async function check(name: string, fn: () => Promise<void> | void): Promise<void> {
  try {
    await fn();
    console.log(`  PASS  ${name}`);
    passed++;
  } catch (err) {
    console.log(`  FAIL  ${name}`);
    console.log(`        ${err instanceof Error ? err.message : String(err)}`);
    failed++;
    failures.push(name);
  }
}

function assert(condition: boolean, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function requireFixture(name: string): Buffer {
  const path = resolve(FIXTURES_DIR, name);
  if (!existsSync(path)) {
    throw new Error(`Missing fixture ${name} — run: npx tsx scripts/generateTestFixtures.ts`);
  }
  return readFileSync(path);
}

function toArrayBuffer(buf: Buffer): ArrayBuffer {
  return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

// A 1x1 transparent PNG data URL, standing in for a rasterized page image
// (real rasterization needs a browser canvas — see file header).
const STUB_PNG_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';

/** Mirrors usePdfRenderer.extractPositionedText for a Node-side test (no `page.render()` needed). */
async function extractPositionedTextNode(pdfBuffer: Buffer): Promise<PositionedPageText[]> {
  const doc = await getDocument({ data: new Uint8Array(pdfBuffer) }).promise;
  const pages: PositionedPageText[] = [];
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const viewport = page.getViewport({ scale: 1 });
    const textContent = await page.getTextContent();
    const items = (textContent.items as any[])
      .filter((it) => 'str' in it && it.str.trim() !== '')
      .map((it) => ({
        text: it.str,
        xPt: it.transform[4],
        yPt: it.transform[5],
        fontSizePt: Math.hypot(it.transform[2], it.transform[3]) || 12,
      }));
    pages.push({ pageNumber: i, widthPt: viewport.width, heightPt: viewport.height, items });
  }
  // short-lived Node script — no destroy() on this pdfjs build's doc proxy, and none is needed here
  return pages;
}

/** Mirrors usePdfRenderer.extractStyledParagraphs for a Node-side test. */
async function extractStyledParagraphsNode(pdfBuffer: Buffer): Promise<StyledPageText[]> {
  const doc = await getDocument({ data: new Uint8Array(pdfBuffer) }).promise;
  const pages: StyledPageText[] = [];
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i);
    const textContent = await page.getTextContent();
    const rawItems = (textContent.items as any[]).filter((it) => 'str' in it);

    const paragraphs: Array<{ text: string; fontSizePt: number }> = [];
    let currentText = '';
    let currentSizes: number[] = [];
    let prevY: number | null = null;
    const flush = () => {
      const text = currentText.trim();
      if (text) {
        const avgSize = currentSizes.reduce((a, b) => a + b, 0) / Math.max(1, currentSizes.length);
        paragraphs.push({ text, fontSizePt: avgSize || 12 });
      }
      currentText = '';
      currentSizes = [];
    };
    for (const item of rawItems) {
      if (item.str === '') continue;
      const y = item.transform[5];
      const size = Math.hypot(item.transform[2], item.transform[3]) || 12;
      const h = item.height || size || 10;
      if (prevY === null) {
        currentText = item.str;
      } else {
        const gap = Math.abs(prevY - y);
        if (gap > h * 1.6) {
          flush();
          currentText = item.str;
        } else if (gap > h * 0.3) {
          currentText += ' ' + item.str;
        } else {
          currentText += item.str;
        }
      }
      currentSizes.push(size);
      prevY = y;
    }
    flush();
    pages.push({ pageNumber: i, paragraphs });
  }
  // short-lived Node script — no destroy() on this pdfjs build's doc proxy, and none is needed here
  return pages;
}

async function main() {
  console.log('IHatePDF — end-to-end feature verification\n');

  const pptxBuffer = requireFixture('sample-presentation.pptx');
  const docxBuffer = requireFixture('sample-document.docx');
  const pdfBuffer = requireFixture('sample-multi.pdf');

  console.log('Organize category');
  await check('Merge PDF: 2 files -> page count = sum of inputs', async () => {
    const single = await PDFDocument.create();
    single.addPage([300, 300]);
    const singleBytes = toArrayBuffer(Buffer.from(await single.save()));
    const result = await mergePdfs([
      { name: 'a.pdf', buffer: toArrayBuffer(pdfBuffer) }, // 4 pages
      { name: 'b.pdf', buffer: singleBytes }, // 1 page
    ]);
    assert(result.pageCount === 5, `expected 5 pages, got ${result.pageCount}`);
    const reloaded = await PDFDocument.load(result.buffer);
    assert(reloaded.getPageCount() === 5, 'merged buffer does not actually contain 5 pages');
  });

  await check('Split PDF: range 1-2 -> 2-page output', async () => {
    const result = await splitPdf(toArrayBuffer(pdfBuffer), 'sample-multi.pdf', [{ from: 1, to: 2 }]);
    assert(result.pageCount === 2, `expected 2 pages, got ${result.pageCount}`);
    const reloaded = await PDFDocument.load(result.buffer);
    assert(reloaded.getPageCount() === 2, 'split buffer does not actually contain 2 pages');
  });

  await check('Split PDF: "all" -> ZIP with one entry per page', async () => {
    const result = await splitPdf(toArrayBuffer(pdfBuffer), 'sample-multi.pdf', 'all');
    assert(result.fileName.endsWith('.zip'), 'expected a .zip result for burst mode');
    const entries = await readZip(new Uint8Array(result.buffer));
    assert(entries.size === 4, `expected 4 zip entries, got ${entries.size}`);
  });

  await check('Rotate PDF: 90° global -> page rotation angle updates', async () => {
    const result = await rotatePdfPages(toArrayBuffer(pdfBuffer), 'sample-multi.pdf', [], 90);
    const reloaded = await PDFDocument.load(result.buffer);
    const angle = reloaded.getPage(0).getRotation().angle;
    assert(angle === 90, `expected page 0 rotation 90, got ${angle}`);
  });

  await check('Organize PDF: reorder + delete -> output matches target sequence', async () => {
    // Reverse pages [3,2,1,0] and delete original index 1.
    const result = await organizePdfPages(toArrayBuffer(pdfBuffer), 'sample-multi.pdf', [3, 2, 1, 0], [1]);
    assert(result.pageCount === 3, `expected 3 pages after reorder+delete, got ${result.pageCount}`);
  });

  console.log('\nOptimize category');
  await check('Compress PDF: output is valid and metadata is stripped', async () => {
    const result = await compressPdf(toArrayBuffer(pdfBuffer), 'sample-multi.pdf', 'recommended');
    const reloaded = await PDFDocument.load(result.buffer);
    assert(reloaded.getPageCount() === 4, 'compressed document lost pages');
    assert(reloaded.getTitle() === '' || reloaded.getTitle() === undefined, 'title metadata was not stripped');
  });

  console.log('\nHigh-fidelity conversions');
  await check('pptxParser: theme + slide 1 background/table/colors parsed correctly', async () => {
    const entries = await readZip(new Uint8Array(pptxBuffer));
    const decoder = new TextDecoder();
    const theme = parseTheme(decoder.decode(entries.get('ppt/theme/theme1.xml')!));
    const slideSize = parseSlideSize(decoder.decode(entries.get('ppt/presentation.xml')!));
    assert(slideSize.widthPt > 0 && slideSize.heightPt > 0, 'slide size did not parse');

    const slide1 = parseSlide(decoder.decode(entries.get('ppt/slides/slide1.xml')!), theme);
    assert(slide1.tables.length === 1, `expected 1 table on slide 1, found ${slide1.tables.length}`);
    assert(slide1.tables[0].rows.length === 3, `expected 3 table rows (incl. header), found ${slide1.tables[0].rows.length}`);
    assert(slide1.tables[0].rows[0].length === 2, 'expected 2 table columns');

    const headerShape = slide1.shapes.find((s) => s.paragraphs.some((p) => p.runs.some((r) => r.text.includes('Quarterly Report'))));
    assert(!!headerShape, 'colored header text shape not found');
    const headerRun = headerShape!.paragraphs[0].runs.find((r) => r.text.includes('Quarterly Report'))!;
    assert(
      headerRun.color.r === 0xe1 && headerRun.color.g === 0x1d && headerRun.color.b === 0x48,
      `expected header run color #E11D48, got rgb(${headerRun.color.r},${headerRun.color.g},${headerRun.color.b})`
    );
    assert(headerRun.bold === true, 'header run should be bold');

    const shapeFill = slide1.shapes.find((s) => s.fill.kind === 'solid' && s.paragraphs.length === 0);
    assert(!!shapeFill, 'vector shape (colored rectangle, no text) not found');
  });

  await check('pptxParser: slide 2 gradient background parsed with real stops', async () => {
    const entries = await readZip(new Uint8Array(pptxBuffer));
    const decoder = new TextDecoder();
    const theme = parseTheme(decoder.decode(entries.get('ppt/theme/theme1.xml')!));
    const slide2 = parseSlide(decoder.decode(entries.get('ppt/slides/slide2.xml')!), theme);
    assert(slide2.background.kind === 'gradient', `expected gradient background, got ${slide2.background.kind}`);
    if (slide2.background.kind === 'gradient') {
      assert(slide2.background.stops.length === 2, 'expected 2 gradient stops');
    }
    assert(slide2.shapes.length >= 2, `expected >=2 positioned text shapes (two columns), found ${slide2.shapes.length}`);
  });

  await check('pptxParser: slide 3 placeholder inheritance and image extraction parsed correctly', async () => {
    const entries = await readZip(new Uint8Array(pptxBuffer));
    const decoder = new TextDecoder();
    const theme = parseTheme(decoder.decode(entries.get('ppt/theme/theme1.xml')!));
    const layoutXml = decoder.decode(entries.get('ppt/slideLayouts/slideLayout1.xml')!);
    const slide3 = parseSlide(decoder.decode(entries.get('ppt/slides/slide3.xml')!), theme, layoutXml);

    assert(slide3.shapes.length >= 2, `expected >= 2 shapes (title placeholder + body), found ${slide3.shapes.length}`);
    const titleShape = slide3.shapes.find((s) => s.paragraphs.some((p) => p.runs.some((r) => r.text.includes('Placeholder Slide Title'))));
    assert(!!titleShape, 'title shape from layout placeholder was dropped');
    assert(titleShape.widthPt > 0 && titleShape.heightPt > 0, 'placeholder title has zero dimensions');

    const bodyShape = slide3.shapes.find((s) => s.paragraphs.some((p) => p.runs.some((r) => r.text.includes('line three'))));
    assert(!!bodyShape, 'body text shape was dropped');

    assert(slide3.images.length === 1, `expected 1 extracted image (<p:pic>), found ${slide3.images.length}`);
    assert(slide3.images[0].rId === 'rId2', `expected image rId rId2, got ${slide3.images[0].rId}`);
  });

  await check('PPTX -> PDF: 3 slides, skips orphaned slide99, renders placeholders, multiline text and images', async () => {
    const result = await convertPptxToPdf(toArrayBuffer(pptxBuffer), 'sample-presentation.pptx');
    const reloaded = await PDFDocument.load(result.buffer);
    assert(reloaded.getPageCount() === 3, `expected exactly 3 PDF pages (orphaned slide99 skipped), got ${reloaded.getPageCount()}`);
    const page = reloaded.getPage(0);
    const { width, height } = page.getSize();
    assert(width > 600 && height > 300, `slide dimensions look wrong: ${width}x${height}`);

    // Verify slide 3 text in converted PDF
    const pages = await extractStyledParagraphsNode(Buffer.from(result.buffer));
    const page3 = pages[2];
    assert(!!page3, 'page 3 missing from extracted text');
    const page3Text = page3.paragraphs.map((p) => p.text).join(' ');
    assert(page3Text.includes('Placeholder Slide Title'), 'slide 3 title missing from converted PDF');
    assert(page3Text.includes('line three that should never be truncated'), 'slide 3 multiline text was truncated/lost');
  });

  await check('DOCX -> PDF fidelity: mammoth resolves named styles this app maps to real CSS', async () => {
    // The app calls mammoth with `{ arrayBuffer }` (correct for the browser
    // bundle Vite ships to the client); mammoth's plain Node entrypoint
    // only recognizes `{ buffer }` — this Node-side check uses that form.
    const mammoth = (await import('mammoth')).default;
    const { value: html } = await mammoth.convertToHtml(
      { buffer: docxBuffer },
      {
        styleMap: [
          "p[style-name='Title'] => h1.docx-title:fresh",
          "p[style-name='Callout'] => p.docx-callout:fresh",
        ],
      }
    );
    assert(html.includes('docx-title'), 'Title style did not map to the expected class');
    assert(html.includes('docx-callout'), 'Callout style did not map to the expected class');
    assert(html.includes('<strong>'), 'bold run was not preserved');
    assert(html.includes('<em>'), 'italic run was not preserved');
    assert(html.includes('<table>'), 'invoice table was not preserved as a real HTML table');
    assert(html.includes('Total due'), 'body text missing from conversion');
  });

  await check('PDF -> Word: headings detected by real font size, valid docx produced', async () => {
    const pages = await extractStyledParagraphsNode(pdfBuffer);
    assert(pages.length === 4, `expected 4 pages of extracted text, got ${pages.length}`);
    const result = await buildDocxFromPages(pages, 'sample-multi.pdf');
    assert(result.buffer.byteLength > 0, 'docx output is empty');
    assert(result.mimeType.includes('wordprocessingml'), 'unexpected mime type for docx output');
  });

  await check('PDF -> PPTX: real positioned text frames from actual PDF coordinates', async () => {
    const pageText = await extractPositionedTextNode(pdfBuffer);
    assert(pageText.some((p) => p.items.length > 0), 'no positioned text items extracted from PDF');
    const slides = pageText.map((p) => ({ dataUrl: STUB_PNG_DATA_URL, widthPt: p.widthPt, heightPt: p.heightPt }));
    const result = await buildPptxFromPages(slides, pageText, 'sample-multi.pdf');
    assert(result.buffer.byteLength > 0, 'pptx output is empty');
    const entries = await readZip(new Uint8Array(result.buffer));
    const slideXmls = Array.from(entries.keys()).filter((n) => /^ppt\/slides\/slide\d+\.xml$/.test(n));
    assert(slideXmls.length === 4, `expected 4 slides, found ${slideXmls.length}`);
    const decoder = new TextDecoder();
    const slide1Xml = decoder.decode(entries.get('ppt/slides/slide1.xml')!);
    assert(slide1Xml.includes('Fixture Document') || slide1Xml.includes('Page 1'), 'expected real extracted PDF text in the pptx slide XML');
  });

  await check('Excel -> PDF: real workbook with borders converts to a valid multi-cell PDF', async () => {
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet([
      ['Item', 'Qty', 'Price'],
      ['Widget', 4, 12.5],
      ['Gadget', 2, 40],
    ]);
    XLSX.utils.book_append_sheet(wb, ws, 'Invoice');
    const xlsxBuffer: Buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });

    const result = await convertXlsxToPdf(toArrayBuffer(xlsxBuffer), 'invoice.xlsx');
    const reloaded = await PDFDocument.load(result.buffer);
    assert(reloaded.getPageCount() >= 1, 'expected at least 1 PDF page from the workbook');
  });

  console.log(`\n${passed} passed, ${failed} failed (${passed + failed} run)\n`);

  if (failed > 0) {
    console.log('Failed checks:');
    failures.forEach((f) => console.log(`  - ${f}`));
    process.exit(1);
  }
}

main().catch((err) => {
  console.error('Test run crashed:', err);
  process.exit(1);
});
